# mange dependencies with brew https://brew.sh/

#
# Virtualization
#
brew 'colima'               # Container runtimes on MacOS (and Linux) with
                            # minimal setup
                            # https://github.com/abiosoft/colima/blob/main/README.md
brew 'docker'               # Pack, ship and run any application as a
                            # lightweight container https://www.docker.com/
brew 'docker-compose'       # Isolated development environments using Docker
                            # https://docs.docker.com/compose/
brew 'localstack'           # Fully functional local AWS cloud stack
                            # https://localstack.cloud/